apiVersion: apps/v1
kind: PersistentVolume
metadata:
  name: webapp-pv
  labels:
    name: database-volume
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
