apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pvc
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolume
    name: webapp-pv



