apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  database-pvc
  labels:
    name:  database-volume
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolume
    name: database-pv

