apiVersion: apps/v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle